### ISSUE TITLE
Feedback for “Introduction” - WHERE IS DOCUMENTATION ON AUTHENTICATION

### ISSUE THREAD

**Issue by RchaTrident** [cosmostation/cosmostation-docs#13]
title says all.

**Comment by bigshooTer39** [comment]
Authentication for api key?

**Comment by RchaTrident** [comment]
How to approve to get API key? I need one approved please


River Cha

Blockchain Engineer

1100 Abernathy Road NE

500 Northpark Building, Suite 300

Atlanta, GA 30328, USA

***@***.***

www.tridenttrust.com<http://www.tridenttrust.com/>



[Trident Trust Master Logo_CMYK_300]



The information in this email and any attachments is confidential and may be privileged or protected by other legal rules.  It is intended solely for the addressee(s).  Access to this e-mail by anyone other than the addressee(s) is unauthorized.  If you are not the intended recipient, you are not authorized to and therefore must not disclose, copy, distribute or retain this message or any part of this message. All members of the Trident Trust Group are committed to holding and using Personal Data responsibly and securely and process Personal Data in accordance with applicable data protection law. For further information and to download our Fair Processing Notice, visit https://tridenttrust.com/legal-pages/data-protection/.

________________________________

**Comment by soaryong-c** [comment]
@RchaTrident @bigshooTer39 
As this is currently a beta service, authorization is being processed via email.
I have added the mentioned content to the docs.
https://docs.cosmostation.io/apis

Thank you for providing feedback.

**Comment by RchaTrident** [comment]
how do I get my api key approved?

River Cha
Blockchain Engineer
Trident Fund Services, Inc.
Direct:  678-438-7260
www.tridenttrust.com<http://www.tridenttrust.com/>

[Trident Trust Master Logo_CMYK_300]

The information in this email and any attachments is confidential and may be privileged or protected by other legal rules.  It is intended solely for the addressee(s).  Access to this e-mail by anyone other than the addressee(s) is unauthorized.  If you are not the intended recipient, you are not authorized to and therefore must not disclose, copy, distribute or retain this message or any part of this message.  All members of the Trident Trust Group are committed to holding and using Personal Data responsibly and securely and process Personal Data in accordance with applicable data protection law. For further information and to download our Fair Processing Notice, visit https://tridenttrust.com/legal-pages/data-protection/.



________________________________

**Comment by soaryong-c** [comment]
can you send email api@cosmostation.io ?
