### ISSUE TITLE
How to obtain full api key and move out of pending status?

### ISSUE THREAD

**Issue by bigshooTer39** [cosmostation/cosmostation-docs#14]
I have my account setup and created an api key, however it say pending next to the api key.  I'm not able to copy and paste it because the middle characters of the key are suppressed with "...".  There's no option to view the full key.

1.) How do I view the full api key?
2.) How do I move the api key out of pending status?  I see no mention of the api keys at all in the documentation.  I also tried searching github without any luck.  I don't see a discord either to contact support.   

Would love to use this.  I spend hours upon hours downloading and transforming transactions.

**Comment by soaryong-c** [comment]
@bigshooTer39 
Sorry for the late answer.
The ability to check the API key will be improved in the next release.
As this is currently a beta service, authorization is being processed via email.
I have added the mentioned content to the docs.
https://docs.cosmostation.io/apis

Thank you for providing feedback.
