### ISSUE TITLE
Feedback for “Account”

### ISSUE THREAD

**Issue by laroussev** [cosmostation/cosmostation-docs#22]
In the api section, I write my sent15jm88z8fex5ysxk94mzukx9au5svvx8fr4qkp9 address in the cosmos address section in the block chain section, but I cannot see my Total balance or how many dvp ttoken I have. 
https://www.mintscan.io/sentinel/address/sent15jm88z8fex5ysxk94mzukx9au5svvx8fr4qkp9 
I can see everything in my account from this link

**Comment by juniahn-dev** [comment]
hi @laroussev appreciate your attention for our api service.

api service currently does not support sentinel chain, so you can't query sentinel address yet.

we plan to support sentinel chain in the future.
please continue to pay attention. thank you.
