### ISSUE TITLE
account transactions api only goes back to 11/20/23 (or so)

### ISSUE THREAD

**Issue by hodgerpodger** [cosmostation/cosmostation-docs#23]
Hello,

More of a question than issue: does the account transactions api only go back to 11/20/23 or so?  

Example of api I'm trying:
  * https://apis.mintscan.io/v1/osmosis/accounts/osmo1clf5zxzks4zgq9ahvyulmurc3cvxl580jvds5k/transactions
  * https://apis.mintscan.io/v1/osmosis/accounts/osmo1clf5zxzks4zgq9ahvyulmurc3cvxl580jvds5k/transactions?searchAfter=MTcwMTAzNDY1NDAwMHwxMjUxNzUyNnw3NjZGQjlBRDZFNDc5MTQ5RUM2NzlEQ0Y0MDhCQzRBRkZCRjFEOUJFMEFFNzFFQzY4OEI4NjU1ODc4NEFDODRE

I've successfully gotten some results for several addresses across osmosis, cosmos, and juno, but looks like transactions consistently only go back to 11/20/23 or so. 

A few questions along this line:

* Transactions only go back to 11/20/23 (or so) for account transactions api?
* If so, any plans to expand farther back before 11/20/23?
* If limited history, may I assume history will be permanent at 11/20/23 (i.e. it's not a moving target of the last 30 days)?

Thanks for your time and API!

**Comment by juniahn-dev** [comment]
Hello @hodgerpodger 

You can get all time account transactions.
Basically, if you do not specify fromDateTime, we support only querying in units of one month.

So If you want another legacy transactions (after 11/20/23), You have to enter fromDateTime.
Like this!
[https://apis.mintscan.io/v1/osmosis/accounts/osmo1clf5zxzks4zgq9ahvyulmurc3cvxl580jvds5k/transactions?fromDateTime=2023-10-01&searchAfter=MTcwMTAzNDY1NDAwMHwxMjUxNzUyNnw3NjZGQjlBRDZFNDc5MTQ5RUM2NzlEQ0Y0MDhCQzRBRkZCRjFEOUJFMEFFNzFFQzY4OEI4NjU1ODc4NEFDODRE](https://apis.mintscan.io/v1/osmosis/accounts/osmo1clf5zxzks4zgq9ahvyulmurc3cvxl580jvds5k/transactions?fromDateTime=2023-10-01&searchAfter=MTcwMTAzNDY1NDAwMHwxMjUxNzUyNnw3NjZGQjlBRDZFNDc5MTQ5RUM2NzlEQ0Y0MDhCQzRBRkZCRjFEOUJFMEFFNzFFQzY4OEI4NjU1ODc4NEFDODRE)

Trying query!
Thank you for using api service!
