### ISSUE TITLE
Feedback for “Account Balance History”

### ISSUE THREAD

**Issue by Seoulcalibur** [cosmostation/cosmostation-docs#24]
What is the frequency at which account balance snapshots are updated? I'm looking to access the most up-to-date data, but it appears that the available information is only a few days old

**Comment by juniahn-dev** [comment]
Hi @Seoulcalibur 

If you transcation did not occurs, you can see only few days old transactions.
Currently, we are collecting when a transaction occurs, and we plan to update it in the future so that we can collect even if a transaction does not occur.

Thank you using our api service.

**Comment by Seoulcalibur** [comment]
Thank you! This is helpful
