### ISSUE TITLE
Feedback for “Contract Verification”

### ISSUE THREAD

**Issue by chad-schwab** [cosmostation/cosmostation-docs#28]
I am looking for an API endpoint for contract verification for kavascan. Prior to the migration to mintscan, there was an etherscan compatible API to get verified contract ABIs. I see you give the ability to verify contracts, but I do not see a way to get that information back out.

**Comment by ong-ar** [comment]
After signing up at `https://docs.cosmostation.io/apis` and generating an API key, you can retrieve the information using the following endpoints:

`https://docs.cosmostation.io/apis/reference-evm/contract/abi`
`https://docs.cosmostation.io/apis/reference-evm/contract/source-code`
