### ISSUE TITLE
Feedback for “Transaction List”

### ISSUE THREAD

**Issue by Marrrrrrrrrrtin** [cosmostation/cosmostation-docs#32]
When I request the transaction history of Akash transaction history, the feedback is 401 (invalid token), but my token was consumed. 
<img width="1440" alt="Screenshot 2024-07-15 at 10 53 26" src="https://github.com/user-attachments/assets/22e3475f-b1ca-486f-a95f-1bf61fa3c195">
<img width="1440" alt="Screenshot 2024-07-15 at 10 53 32" src="https://github.com/user-attachments/assets/5ca494d6-2764-4c82-a5aa-41518ff55e56">

**Comment by ong-ar** [comment]
Currently in beta, approval is being processed via email(api@cosmostation.io).
