### ISSUE TITLE
Feedback for “Prices” - toDateTime mangles input

### ISSUE THREAD

**Issue by ericm301** [cosmostation/cosmostation-docs#36]
The API tester is not translating the toDateTime input properly.
URL: /v1/prices/symbol/:symbol
Enter 2024-10-15 for the date, retrieve result from URL
- https://apis.mintscan.io/v1/prices/symbol/uosmo?toDateTime=2024-10-15
- response success

Enter 2024-10-15 20:00:00 into toDateTime, result URL
- https://apis.mintscan.io/v1/prices/symbol/uosmo?toDateTime=2024-10-15%2020%3A00%3A00
- BAD REQUEST: toDateTime must be a valid ISO-8601 date string.

Edit: I just tested the endpoint with ThunderClient and it works, so something on the page is wrong.

**Comment by ericm301** [comment]
This still doesn't work. The API is working, but the component is incorrectly parsing the input:
![image](https://github.com/user-attachments/assets/c032b48e-18bf-4e91-815f-dfbc379c4813)

**Comment by ericm301** [comment]
Hello?

**Comment by ong-ar** [comment]
@ericm301 

Thank you for your attention to this matter. Upon checking, we found an issue where URI encoding was being applied twice on the page. This has been fixed and successfully deployed.
