### ISSUE TITLE
Feedback for “Account Balance History”

### ISSUE THREAD

**Issue by ericm301** [cosmostation/cosmostation-docs#37]
Transactions after 2024-10-31 are not loading.

Expected behavior:
* All transactions should be shown, most recent first.

Actual behavior:
* Only txs before 2024-11-01 are retrieved
* No tx are shown for November

NOTE: The endpoint does retrieve values, so it's not an auth problem.

**Comment by ericm301** [comment]
Anybody?

**Comment by ong-ar** [comment]
@ericm301 

If fromDateTime and toDateTime are not provided, the default is set to retrieve data for a one-month period from the current date. Adding specific values for these parameters will allow you to customize the date range as needed.

**Comment by ericm301** [comment]
Here's my call, with no parameters:

    curl  -X GET \
    'https://apis.mintscan.io/v1/osmosis/accounts/osmo1m....9p5/balances' \
    --header 'Accept: */*' \
    --header 'User-Agent: Thunder Client (https://www.thunderclient.com)' \
    --header 'Authorization: Bearer {{mintApiKey}}`

This gives me seemingly random results, all before 2024-11-02. Sometimes, it gives me 11-01, sometimes 10-31, sometimes earlier. It does seem that successive requests tend to older results.

I am not adding any query parameters to the avove requests. This, as mentioned above, should return the most recent 20 balance entries. I have about 15 transactions on this address since 2024-11-01, each of which should have an entry in the responses.

If I add `fromDateTime=2024-11-01&toDateTime=2024-11-10` to my request, I only get one result, for 2024-11-01.

**Comment by ong-ar** [comment]
@ericm301 

We are currently operating with physically distributed databases and have encountered a data inconsistency issue. We are actively working to resolve this synchronization bug. Thank you for notifying us of this matter.

**Comment by ericm301** [comment]
The data seems to be slowly catching up; it's at 2024-11-14 right now.

**Comment by wannabit-yongjoo** [comment]
@ong-ar

**Comment by chicrock** [comment]
We encountered some issues while updating the asset data structure.
We're currently working to catch up on the data, and it will be updated soon.

However, historical data from 11/14 to today may be lost.

Thanks.
