### ISSUE TITLE
Feedback for “Assets”

### ISSUE THREAD

**Issue by samuel-poon** [cosmostation/cosmostation-docs#7]
Is there an endpoint that shows all supported networks and their identifier for the Mintscan API? I have tried /v1/:network/assets using some networks like akash, axelar, kava, quicksilver but keep getting the NOT_SUPPORTED_CHAIN message. Would be helpful if there was an easy way to retrieve this.

**Comment by soaryong-c** [comment]
@samuel-poon 
Sorry for the late answer.
Thank you for providing feedback.
I have added the mentioned content to the document.
https://docs.cosmostation.io/apis
