### ISSUE TITLE
Missing Swap Within Batch transactions

### ISSUE THREAD

**Issue by brissenden** [cosmostation/cosmostation-docs#8]
Hi there! I noticed that `/transactions` end-point is not returning Swap transfers. Is there a way to receive it?

E.g. 
https://apis.mintscan.io/v1/cosmos/accounts/cosmos1khrzq4t7r4envst2kgn99wvx0zqkd09kyn8qxx/transactions?fromDateTime=2020-01-01

<img width="1248" alt="cosmos" src="https://github.com/cosmostation/cosmostation-wallet-docs/assets/1084708/e98524f4-5c03-4026-a927-858fb780c7af">

**Comment by soaryong-c** [comment]
@brissenden 
Sorry for the late reply.
Currently, we have confirmed that this part is working normally.
If an error occurs again, please contact us at any time.
Thank you for your feedback.
